// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: presenter_message.proto

#ifndef PROTOBUF_presenter_5fmessage_2eproto__INCLUDED
#define PROTOBUF_presenter_5fmessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_presenter_5fmessage_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[7];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsOpenChannelRequestImpl();
void InitDefaultsOpenChannelRequest();
void InitDefaultsOpenChannelResponseImpl();
void InitDefaultsOpenChannelResponse();
void InitDefaultsHeartbeatMessageImpl();
void InitDefaultsHeartbeatMessage();
void InitDefaultsCoordinateImpl();
void InitDefaultsCoordinate();
void InitDefaultsRectangle_AttrImpl();
void InitDefaultsRectangle_Attr();
void InitDefaultsPresentImageRequestImpl();
void InitDefaultsPresentImageRequest();
void InitDefaultsPresentImageResponseImpl();
void InitDefaultsPresentImageResponse();
inline void InitDefaults() {
  InitDefaultsOpenChannelRequest();
  InitDefaultsOpenChannelResponse();
  InitDefaultsHeartbeatMessage();
  InitDefaultsCoordinate();
  InitDefaultsRectangle_Attr();
  InitDefaultsPresentImageRequest();
  InitDefaultsPresentImageResponse();
}
}  // namespace protobuf_presenter_5fmessage_2eproto
namespace ascend {
namespace presenter {
namespace proto {
class Coordinate;
class CoordinateDefaultTypeInternal;
extern CoordinateDefaultTypeInternal _Coordinate_default_instance_;
class HeartbeatMessage;
class HeartbeatMessageDefaultTypeInternal;
extern HeartbeatMessageDefaultTypeInternal _HeartbeatMessage_default_instance_;
class OpenChannelRequest;
class OpenChannelRequestDefaultTypeInternal;
extern OpenChannelRequestDefaultTypeInternal _OpenChannelRequest_default_instance_;
class OpenChannelResponse;
class OpenChannelResponseDefaultTypeInternal;
extern OpenChannelResponseDefaultTypeInternal _OpenChannelResponse_default_instance_;
class PresentImageRequest;
class PresentImageRequestDefaultTypeInternal;
extern PresentImageRequestDefaultTypeInternal _PresentImageRequest_default_instance_;
class PresentImageResponse;
class PresentImageResponseDefaultTypeInternal;
extern PresentImageResponseDefaultTypeInternal _PresentImageResponse_default_instance_;
class Rectangle_Attr;
class Rectangle_AttrDefaultTypeInternal;
extern Rectangle_AttrDefaultTypeInternal _Rectangle_Attr_default_instance_;
}  // namespace proto
}  // namespace presenter
}  // namespace ascend
namespace ascend {
namespace presenter {
namespace proto {

enum OpenChannelErrorCode {
  kOpenChannelErrorNone = 0,
  kOpenChannelErrorNoSuchChannel = 1,
  kOpenChannelErrorChannelAlreadyOpened = 2,
  kOpenChannelErrorOther = -1,
  OpenChannelErrorCode_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  OpenChannelErrorCode_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool OpenChannelErrorCode_IsValid(int value);
const OpenChannelErrorCode OpenChannelErrorCode_MIN = kOpenChannelErrorOther;
const OpenChannelErrorCode OpenChannelErrorCode_MAX = kOpenChannelErrorChannelAlreadyOpened;
const int OpenChannelErrorCode_ARRAYSIZE = OpenChannelErrorCode_MAX + 1;

const ::google::protobuf::EnumDescriptor* OpenChannelErrorCode_descriptor();
inline const ::std::string& OpenChannelErrorCode_Name(OpenChannelErrorCode value) {
  return ::google::protobuf::internal::NameOfEnum(
    OpenChannelErrorCode_descriptor(), value);
}
inline bool OpenChannelErrorCode_Parse(
    const ::std::string& name, OpenChannelErrorCode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<OpenChannelErrorCode>(
    OpenChannelErrorCode_descriptor(), name, value);
}
enum ChannelContentType {
  kChannelContentTypeImage = 0,
  kChannelContentTypeVideo = 1,
  ChannelContentType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ChannelContentType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ChannelContentType_IsValid(int value);
const ChannelContentType ChannelContentType_MIN = kChannelContentTypeImage;
const ChannelContentType ChannelContentType_MAX = kChannelContentTypeVideo;
const int ChannelContentType_ARRAYSIZE = ChannelContentType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ChannelContentType_descriptor();
inline const ::std::string& ChannelContentType_Name(ChannelContentType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ChannelContentType_descriptor(), value);
}
inline bool ChannelContentType_Parse(
    const ::std::string& name, ChannelContentType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ChannelContentType>(
    ChannelContentType_descriptor(), name, value);
}
enum ImageFormat {
  kImageFormatJpeg = 0,
  ImageFormat_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ImageFormat_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ImageFormat_IsValid(int value);
const ImageFormat ImageFormat_MIN = kImageFormatJpeg;
const ImageFormat ImageFormat_MAX = kImageFormatJpeg;
const int ImageFormat_ARRAYSIZE = ImageFormat_MAX + 1;

const ::google::protobuf::EnumDescriptor* ImageFormat_descriptor();
inline const ::std::string& ImageFormat_Name(ImageFormat value) {
  return ::google::protobuf::internal::NameOfEnum(
    ImageFormat_descriptor(), value);
}
inline bool ImageFormat_Parse(
    const ::std::string& name, ImageFormat* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ImageFormat>(
    ImageFormat_descriptor(), name, value);
}
enum PresentDataErrorCode {
  kPresentDataErrorNone = 0,
  kPresentDataErrorUnsupportedType = 1,
  kPresentDataErrorUnsupportedFormat = 2,
  kPresentDataErrorOther = -1,
  PresentDataErrorCode_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  PresentDataErrorCode_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool PresentDataErrorCode_IsValid(int value);
const PresentDataErrorCode PresentDataErrorCode_MIN = kPresentDataErrorOther;
const PresentDataErrorCode PresentDataErrorCode_MAX = kPresentDataErrorUnsupportedFormat;
const int PresentDataErrorCode_ARRAYSIZE = PresentDataErrorCode_MAX + 1;

const ::google::protobuf::EnumDescriptor* PresentDataErrorCode_descriptor();
inline const ::std::string& PresentDataErrorCode_Name(PresentDataErrorCode value) {
  return ::google::protobuf::internal::NameOfEnum(
    PresentDataErrorCode_descriptor(), value);
}
inline bool PresentDataErrorCode_Parse(
    const ::std::string& name, PresentDataErrorCode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PresentDataErrorCode>(
    PresentDataErrorCode_descriptor(), name, value);
}
// ===================================================================

class OpenChannelRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ascend.presenter.proto.OpenChannelRequest) */ {
 public:
  OpenChannelRequest();
  virtual ~OpenChannelRequest();

  OpenChannelRequest(const OpenChannelRequest& from);

  inline OpenChannelRequest& operator=(const OpenChannelRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  OpenChannelRequest(OpenChannelRequest&& from) noexcept
    : OpenChannelRequest() {
    *this = ::std::move(from);
  }

  inline OpenChannelRequest& operator=(OpenChannelRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const OpenChannelRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const OpenChannelRequest* internal_default_instance() {
    return reinterpret_cast<const OpenChannelRequest*>(
               &_OpenChannelRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(OpenChannelRequest* other);
  friend void swap(OpenChannelRequest& a, OpenChannelRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline OpenChannelRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  OpenChannelRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const OpenChannelRequest& from);
  void MergeFrom(const OpenChannelRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(OpenChannelRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string channel_name = 1;
  void clear_channel_name();
  static const int kChannelNameFieldNumber = 1;
  const ::std::string& channel_name() const;
  void set_channel_name(const ::std::string& value);
  #if LANG_CXX11
  void set_channel_name(::std::string&& value);
  #endif
  void set_channel_name(const char* value);
  void set_channel_name(const char* value, size_t size);
  ::std::string* mutable_channel_name();
  ::std::string* release_channel_name();
  void set_allocated_channel_name(::std::string* channel_name);

  // .ascend.presenter.proto.ChannelContentType content_type = 2;
  void clear_content_type();
  static const int kContentTypeFieldNumber = 2;
  ::ascend::presenter::proto::ChannelContentType content_type() const;
  void set_content_type(::ascend::presenter::proto::ChannelContentType value);

  // @@protoc_insertion_point(class_scope:ascend.presenter.proto.OpenChannelRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr channel_name_;
  int content_type_;
  mutable int _cached_size_;
  friend struct ::protobuf_presenter_5fmessage_2eproto::TableStruct;
  friend void ::protobuf_presenter_5fmessage_2eproto::InitDefaultsOpenChannelRequestImpl();
};
// -------------------------------------------------------------------

class OpenChannelResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ascend.presenter.proto.OpenChannelResponse) */ {
 public:
  OpenChannelResponse();
  virtual ~OpenChannelResponse();

  OpenChannelResponse(const OpenChannelResponse& from);

  inline OpenChannelResponse& operator=(const OpenChannelResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  OpenChannelResponse(OpenChannelResponse&& from) noexcept
    : OpenChannelResponse() {
    *this = ::std::move(from);
  }

  inline OpenChannelResponse& operator=(OpenChannelResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const OpenChannelResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const OpenChannelResponse* internal_default_instance() {
    return reinterpret_cast<const OpenChannelResponse*>(
               &_OpenChannelResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(OpenChannelResponse* other);
  friend void swap(OpenChannelResponse& a, OpenChannelResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline OpenChannelResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  OpenChannelResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const OpenChannelResponse& from);
  void MergeFrom(const OpenChannelResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(OpenChannelResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string error_message = 2;
  void clear_error_message();
  static const int kErrorMessageFieldNumber = 2;
  const ::std::string& error_message() const;
  void set_error_message(const ::std::string& value);
  #if LANG_CXX11
  void set_error_message(::std::string&& value);
  #endif
  void set_error_message(const char* value);
  void set_error_message(const char* value, size_t size);
  ::std::string* mutable_error_message();
  ::std::string* release_error_message();
  void set_allocated_error_message(::std::string* error_message);

  // .ascend.presenter.proto.OpenChannelErrorCode error_code = 1;
  void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  ::ascend::presenter::proto::OpenChannelErrorCode error_code() const;
  void set_error_code(::ascend::presenter::proto::OpenChannelErrorCode value);

  // @@protoc_insertion_point(class_scope:ascend.presenter.proto.OpenChannelResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr error_message_;
  int error_code_;
  mutable int _cached_size_;
  friend struct ::protobuf_presenter_5fmessage_2eproto::TableStruct;
  friend void ::protobuf_presenter_5fmessage_2eproto::InitDefaultsOpenChannelResponseImpl();
};
// -------------------------------------------------------------------

class HeartbeatMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ascend.presenter.proto.HeartbeatMessage) */ {
 public:
  HeartbeatMessage();
  virtual ~HeartbeatMessage();

  HeartbeatMessage(const HeartbeatMessage& from);

  inline HeartbeatMessage& operator=(const HeartbeatMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  HeartbeatMessage(HeartbeatMessage&& from) noexcept
    : HeartbeatMessage() {
    *this = ::std::move(from);
  }

  inline HeartbeatMessage& operator=(HeartbeatMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const HeartbeatMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const HeartbeatMessage* internal_default_instance() {
    return reinterpret_cast<const HeartbeatMessage*>(
               &_HeartbeatMessage_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(HeartbeatMessage* other);
  friend void swap(HeartbeatMessage& a, HeartbeatMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline HeartbeatMessage* New() const PROTOBUF_FINAL { return New(NULL); }

  HeartbeatMessage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const HeartbeatMessage& from);
  void MergeFrom(const HeartbeatMessage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(HeartbeatMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:ascend.presenter.proto.HeartbeatMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct ::protobuf_presenter_5fmessage_2eproto::TableStruct;
  friend void ::protobuf_presenter_5fmessage_2eproto::InitDefaultsHeartbeatMessageImpl();
};
// -------------------------------------------------------------------

class Coordinate : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ascend.presenter.proto.Coordinate) */ {
 public:
  Coordinate();
  virtual ~Coordinate();

  Coordinate(const Coordinate& from);

  inline Coordinate& operator=(const Coordinate& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Coordinate(Coordinate&& from) noexcept
    : Coordinate() {
    *this = ::std::move(from);
  }

  inline Coordinate& operator=(Coordinate&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Coordinate& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Coordinate* internal_default_instance() {
    return reinterpret_cast<const Coordinate*>(
               &_Coordinate_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(Coordinate* other);
  friend void swap(Coordinate& a, Coordinate& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Coordinate* New() const PROTOBUF_FINAL { return New(NULL); }

  Coordinate* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Coordinate& from);
  void MergeFrom(const Coordinate& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Coordinate* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  ::google::protobuf::uint32 x() const;
  void set_x(::google::protobuf::uint32 value);

  // uint32 y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  ::google::protobuf::uint32 y() const;
  void set_y(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:ascend.presenter.proto.Coordinate)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 x_;
  ::google::protobuf::uint32 y_;
  mutable int _cached_size_;
  friend struct ::protobuf_presenter_5fmessage_2eproto::TableStruct;
  friend void ::protobuf_presenter_5fmessage_2eproto::InitDefaultsCoordinateImpl();
};
// -------------------------------------------------------------------

class Rectangle_Attr : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ascend.presenter.proto.Rectangle_Attr) */ {
 public:
  Rectangle_Attr();
  virtual ~Rectangle_Attr();

  Rectangle_Attr(const Rectangle_Attr& from);

  inline Rectangle_Attr& operator=(const Rectangle_Attr& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Rectangle_Attr(Rectangle_Attr&& from) noexcept
    : Rectangle_Attr() {
    *this = ::std::move(from);
  }

  inline Rectangle_Attr& operator=(Rectangle_Attr&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Rectangle_Attr& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Rectangle_Attr* internal_default_instance() {
    return reinterpret_cast<const Rectangle_Attr*>(
               &_Rectangle_Attr_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(Rectangle_Attr* other);
  friend void swap(Rectangle_Attr& a, Rectangle_Attr& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Rectangle_Attr* New() const PROTOBUF_FINAL { return New(NULL); }

  Rectangle_Attr* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Rectangle_Attr& from);
  void MergeFrom(const Rectangle_Attr& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Rectangle_Attr* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string label_text = 3;
  void clear_label_text();
  static const int kLabelTextFieldNumber = 3;
  const ::std::string& label_text() const;
  void set_label_text(const ::std::string& value);
  #if LANG_CXX11
  void set_label_text(::std::string&& value);
  #endif
  void set_label_text(const char* value);
  void set_label_text(const char* value, size_t size);
  ::std::string* mutable_label_text();
  ::std::string* release_label_text();
  void set_allocated_label_text(::std::string* label_text);

  // .ascend.presenter.proto.Coordinate left_top = 1;
  bool has_left_top() const;
  void clear_left_top();
  static const int kLeftTopFieldNumber = 1;
  const ::ascend::presenter::proto::Coordinate& left_top() const;
  ::ascend::presenter::proto::Coordinate* release_left_top();
  ::ascend::presenter::proto::Coordinate* mutable_left_top();
  void set_allocated_left_top(::ascend::presenter::proto::Coordinate* left_top);

  // .ascend.presenter.proto.Coordinate right_bottom = 2;
  bool has_right_bottom() const;
  void clear_right_bottom();
  static const int kRightBottomFieldNumber = 2;
  const ::ascend::presenter::proto::Coordinate& right_bottom() const;
  ::ascend::presenter::proto::Coordinate* release_right_bottom();
  ::ascend::presenter::proto::Coordinate* mutable_right_bottom();
  void set_allocated_right_bottom(::ascend::presenter::proto::Coordinate* right_bottom);

  // @@protoc_insertion_point(class_scope:ascend.presenter.proto.Rectangle_Attr)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr label_text_;
  ::ascend::presenter::proto::Coordinate* left_top_;
  ::ascend::presenter::proto::Coordinate* right_bottom_;
  mutable int _cached_size_;
  friend struct ::protobuf_presenter_5fmessage_2eproto::TableStruct;
  friend void ::protobuf_presenter_5fmessage_2eproto::InitDefaultsRectangle_AttrImpl();
};
// -------------------------------------------------------------------

class PresentImageRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ascend.presenter.proto.PresentImageRequest) */ {
 public:
  PresentImageRequest();
  virtual ~PresentImageRequest();

  PresentImageRequest(const PresentImageRequest& from);

  inline PresentImageRequest& operator=(const PresentImageRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PresentImageRequest(PresentImageRequest&& from) noexcept
    : PresentImageRequest() {
    *this = ::std::move(from);
  }

  inline PresentImageRequest& operator=(PresentImageRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PresentImageRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PresentImageRequest* internal_default_instance() {
    return reinterpret_cast<const PresentImageRequest*>(
               &_PresentImageRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(PresentImageRequest* other);
  friend void swap(PresentImageRequest& a, PresentImageRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PresentImageRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  PresentImageRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PresentImageRequest& from);
  void MergeFrom(const PresentImageRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PresentImageRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ascend.presenter.proto.Rectangle_Attr rectangle_list = 5;
  int rectangle_list_size() const;
  void clear_rectangle_list();
  static const int kRectangleListFieldNumber = 5;
  const ::ascend::presenter::proto::Rectangle_Attr& rectangle_list(int index) const;
  ::ascend::presenter::proto::Rectangle_Attr* mutable_rectangle_list(int index);
  ::ascend::presenter::proto::Rectangle_Attr* add_rectangle_list();
  ::google::protobuf::RepeatedPtrField< ::ascend::presenter::proto::Rectangle_Attr >*
      mutable_rectangle_list();
  const ::google::protobuf::RepeatedPtrField< ::ascend::presenter::proto::Rectangle_Attr >&
      rectangle_list() const;

  // bytes data = 4;
  void clear_data();
  static const int kDataFieldNumber = 4;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  #if LANG_CXX11
  void set_data(::std::string&& value);
  #endif
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);

  // .ascend.presenter.proto.ImageFormat format = 1;
  void clear_format();
  static const int kFormatFieldNumber = 1;
  ::ascend::presenter::proto::ImageFormat format() const;
  void set_format(::ascend::presenter::proto::ImageFormat value);

  // uint32 width = 2;
  void clear_width();
  static const int kWidthFieldNumber = 2;
  ::google::protobuf::uint32 width() const;
  void set_width(::google::protobuf::uint32 value);

  // uint32 height = 3;
  void clear_height();
  static const int kHeightFieldNumber = 3;
  ::google::protobuf::uint32 height() const;
  void set_height(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:ascend.presenter.proto.PresentImageRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::ascend::presenter::proto::Rectangle_Attr > rectangle_list_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  int format_;
  ::google::protobuf::uint32 width_;
  ::google::protobuf::uint32 height_;
  mutable int _cached_size_;
  friend struct ::protobuf_presenter_5fmessage_2eproto::TableStruct;
  friend void ::protobuf_presenter_5fmessage_2eproto::InitDefaultsPresentImageRequestImpl();
};
// -------------------------------------------------------------------

class PresentImageResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ascend.presenter.proto.PresentImageResponse) */ {
 public:
  PresentImageResponse();
  virtual ~PresentImageResponse();

  PresentImageResponse(const PresentImageResponse& from);

  inline PresentImageResponse& operator=(const PresentImageResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PresentImageResponse(PresentImageResponse&& from) noexcept
    : PresentImageResponse() {
    *this = ::std::move(from);
  }

  inline PresentImageResponse& operator=(PresentImageResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PresentImageResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PresentImageResponse* internal_default_instance() {
    return reinterpret_cast<const PresentImageResponse*>(
               &_PresentImageResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(PresentImageResponse* other);
  friend void swap(PresentImageResponse& a, PresentImageResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PresentImageResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  PresentImageResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PresentImageResponse& from);
  void MergeFrom(const PresentImageResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PresentImageResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string error_message = 2;
  void clear_error_message();
  static const int kErrorMessageFieldNumber = 2;
  const ::std::string& error_message() const;
  void set_error_message(const ::std::string& value);
  #if LANG_CXX11
  void set_error_message(::std::string&& value);
  #endif
  void set_error_message(const char* value);
  void set_error_message(const char* value, size_t size);
  ::std::string* mutable_error_message();
  ::std::string* release_error_message();
  void set_allocated_error_message(::std::string* error_message);

  // .ascend.presenter.proto.PresentDataErrorCode error_code = 1;
  void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  ::ascend::presenter::proto::PresentDataErrorCode error_code() const;
  void set_error_code(::ascend::presenter::proto::PresentDataErrorCode value);

  // @@protoc_insertion_point(class_scope:ascend.presenter.proto.PresentImageResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr error_message_;
  int error_code_;
  mutable int _cached_size_;
  friend struct ::protobuf_presenter_5fmessage_2eproto::TableStruct;
  friend void ::protobuf_presenter_5fmessage_2eproto::InitDefaultsPresentImageResponseImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// OpenChannelRequest

// string channel_name = 1;
inline void OpenChannelRequest::clear_channel_name() {
  channel_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& OpenChannelRequest::channel_name() const {
  // @@protoc_insertion_point(field_get:ascend.presenter.proto.OpenChannelRequest.channel_name)
  return channel_name_.GetNoArena();
}
inline void OpenChannelRequest::set_channel_name(const ::std::string& value) {
  
  channel_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ascend.presenter.proto.OpenChannelRequest.channel_name)
}
#if LANG_CXX11
inline void OpenChannelRequest::set_channel_name(::std::string&& value) {
  
  channel_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ascend.presenter.proto.OpenChannelRequest.channel_name)
}
#endif
inline void OpenChannelRequest::set_channel_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  channel_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ascend.presenter.proto.OpenChannelRequest.channel_name)
}
inline void OpenChannelRequest::set_channel_name(const char* value, size_t size) {
  
  channel_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ascend.presenter.proto.OpenChannelRequest.channel_name)
}
inline ::std::string* OpenChannelRequest::mutable_channel_name() {
  
  // @@protoc_insertion_point(field_mutable:ascend.presenter.proto.OpenChannelRequest.channel_name)
  return channel_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* OpenChannelRequest::release_channel_name() {
  // @@protoc_insertion_point(field_release:ascend.presenter.proto.OpenChannelRequest.channel_name)
  
  return channel_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OpenChannelRequest::set_allocated_channel_name(::std::string* channel_name) {
  if (channel_name != NULL) {
    
  } else {
    
  }
  channel_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), channel_name);
  // @@protoc_insertion_point(field_set_allocated:ascend.presenter.proto.OpenChannelRequest.channel_name)
}

// .ascend.presenter.proto.ChannelContentType content_type = 2;
inline void OpenChannelRequest::clear_content_type() {
  content_type_ = 0;
}
inline ::ascend::presenter::proto::ChannelContentType OpenChannelRequest::content_type() const {
  // @@protoc_insertion_point(field_get:ascend.presenter.proto.OpenChannelRequest.content_type)
  return static_cast< ::ascend::presenter::proto::ChannelContentType >(content_type_);
}
inline void OpenChannelRequest::set_content_type(::ascend::presenter::proto::ChannelContentType value) {
  
  content_type_ = value;
  // @@protoc_insertion_point(field_set:ascend.presenter.proto.OpenChannelRequest.content_type)
}

// -------------------------------------------------------------------

// OpenChannelResponse

// .ascend.presenter.proto.OpenChannelErrorCode error_code = 1;
inline void OpenChannelResponse::clear_error_code() {
  error_code_ = 0;
}
inline ::ascend::presenter::proto::OpenChannelErrorCode OpenChannelResponse::error_code() const {
  // @@protoc_insertion_point(field_get:ascend.presenter.proto.OpenChannelResponse.error_code)
  return static_cast< ::ascend::presenter::proto::OpenChannelErrorCode >(error_code_);
}
inline void OpenChannelResponse::set_error_code(::ascend::presenter::proto::OpenChannelErrorCode value) {
  
  error_code_ = value;
  // @@protoc_insertion_point(field_set:ascend.presenter.proto.OpenChannelResponse.error_code)
}

// string error_message = 2;
inline void OpenChannelResponse::clear_error_message() {
  error_message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& OpenChannelResponse::error_message() const {
  // @@protoc_insertion_point(field_get:ascend.presenter.proto.OpenChannelResponse.error_message)
  return error_message_.GetNoArena();
}
inline void OpenChannelResponse::set_error_message(const ::std::string& value) {
  
  error_message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ascend.presenter.proto.OpenChannelResponse.error_message)
}
#if LANG_CXX11
inline void OpenChannelResponse::set_error_message(::std::string&& value) {
  
  error_message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ascend.presenter.proto.OpenChannelResponse.error_message)
}
#endif
inline void OpenChannelResponse::set_error_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  error_message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ascend.presenter.proto.OpenChannelResponse.error_message)
}
inline void OpenChannelResponse::set_error_message(const char* value, size_t size) {
  
  error_message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ascend.presenter.proto.OpenChannelResponse.error_message)
}
inline ::std::string* OpenChannelResponse::mutable_error_message() {
  
  // @@protoc_insertion_point(field_mutable:ascend.presenter.proto.OpenChannelResponse.error_message)
  return error_message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* OpenChannelResponse::release_error_message() {
  // @@protoc_insertion_point(field_release:ascend.presenter.proto.OpenChannelResponse.error_message)
  
  return error_message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OpenChannelResponse::set_allocated_error_message(::std::string* error_message) {
  if (error_message != NULL) {
    
  } else {
    
  }
  error_message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), error_message);
  // @@protoc_insertion_point(field_set_allocated:ascend.presenter.proto.OpenChannelResponse.error_message)
}

// -------------------------------------------------------------------

// HeartbeatMessage

// -------------------------------------------------------------------

// Coordinate

// uint32 x = 1;
inline void Coordinate::clear_x() {
  x_ = 0u;
}
inline ::google::protobuf::uint32 Coordinate::x() const {
  // @@protoc_insertion_point(field_get:ascend.presenter.proto.Coordinate.x)
  return x_;
}
inline void Coordinate::set_x(::google::protobuf::uint32 value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:ascend.presenter.proto.Coordinate.x)
}

// uint32 y = 2;
inline void Coordinate::clear_y() {
  y_ = 0u;
}
inline ::google::protobuf::uint32 Coordinate::y() const {
  // @@protoc_insertion_point(field_get:ascend.presenter.proto.Coordinate.y)
  return y_;
}
inline void Coordinate::set_y(::google::protobuf::uint32 value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:ascend.presenter.proto.Coordinate.y)
}

// -------------------------------------------------------------------

// Rectangle_Attr

// .ascend.presenter.proto.Coordinate left_top = 1;
inline bool Rectangle_Attr::has_left_top() const {
  return this != internal_default_instance() && left_top_ != NULL;
}
inline void Rectangle_Attr::clear_left_top() {
  if (GetArenaNoVirtual() == NULL && left_top_ != NULL) {
    delete left_top_;
  }
  left_top_ = NULL;
}
inline const ::ascend::presenter::proto::Coordinate& Rectangle_Attr::left_top() const {
  const ::ascend::presenter::proto::Coordinate* p = left_top_;
  // @@protoc_insertion_point(field_get:ascend.presenter.proto.Rectangle_Attr.left_top)
  return p != NULL ? *p : *reinterpret_cast<const ::ascend::presenter::proto::Coordinate*>(
      &::ascend::presenter::proto::_Coordinate_default_instance_);
}
inline ::ascend::presenter::proto::Coordinate* Rectangle_Attr::release_left_top() {
  // @@protoc_insertion_point(field_release:ascend.presenter.proto.Rectangle_Attr.left_top)
  
  ::ascend::presenter::proto::Coordinate* temp = left_top_;
  left_top_ = NULL;
  return temp;
}
inline ::ascend::presenter::proto::Coordinate* Rectangle_Attr::mutable_left_top() {
  
  if (left_top_ == NULL) {
    left_top_ = new ::ascend::presenter::proto::Coordinate;
  }
  // @@protoc_insertion_point(field_mutable:ascend.presenter.proto.Rectangle_Attr.left_top)
  return left_top_;
}
inline void Rectangle_Attr::set_allocated_left_top(::ascend::presenter::proto::Coordinate* left_top) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete left_top_;
  }
  if (left_top) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      left_top = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, left_top, submessage_arena);
    }
    
  } else {
    
  }
  left_top_ = left_top;
  // @@protoc_insertion_point(field_set_allocated:ascend.presenter.proto.Rectangle_Attr.left_top)
}

// .ascend.presenter.proto.Coordinate right_bottom = 2;
inline bool Rectangle_Attr::has_right_bottom() const {
  return this != internal_default_instance() && right_bottom_ != NULL;
}
inline void Rectangle_Attr::clear_right_bottom() {
  if (GetArenaNoVirtual() == NULL && right_bottom_ != NULL) {
    delete right_bottom_;
  }
  right_bottom_ = NULL;
}
inline const ::ascend::presenter::proto::Coordinate& Rectangle_Attr::right_bottom() const {
  const ::ascend::presenter::proto::Coordinate* p = right_bottom_;
  // @@protoc_insertion_point(field_get:ascend.presenter.proto.Rectangle_Attr.right_bottom)
  return p != NULL ? *p : *reinterpret_cast<const ::ascend::presenter::proto::Coordinate*>(
      &::ascend::presenter::proto::_Coordinate_default_instance_);
}
inline ::ascend::presenter::proto::Coordinate* Rectangle_Attr::release_right_bottom() {
  // @@protoc_insertion_point(field_release:ascend.presenter.proto.Rectangle_Attr.right_bottom)
  
  ::ascend::presenter::proto::Coordinate* temp = right_bottom_;
  right_bottom_ = NULL;
  return temp;
}
inline ::ascend::presenter::proto::Coordinate* Rectangle_Attr::mutable_right_bottom() {
  
  if (right_bottom_ == NULL) {
    right_bottom_ = new ::ascend::presenter::proto::Coordinate;
  }
  // @@protoc_insertion_point(field_mutable:ascend.presenter.proto.Rectangle_Attr.right_bottom)
  return right_bottom_;
}
inline void Rectangle_Attr::set_allocated_right_bottom(::ascend::presenter::proto::Coordinate* right_bottom) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete right_bottom_;
  }
  if (right_bottom) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      right_bottom = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, right_bottom, submessage_arena);
    }
    
  } else {
    
  }
  right_bottom_ = right_bottom;
  // @@protoc_insertion_point(field_set_allocated:ascend.presenter.proto.Rectangle_Attr.right_bottom)
}

// string label_text = 3;
inline void Rectangle_Attr::clear_label_text() {
  label_text_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Rectangle_Attr::label_text() const {
  // @@protoc_insertion_point(field_get:ascend.presenter.proto.Rectangle_Attr.label_text)
  return label_text_.GetNoArena();
}
inline void Rectangle_Attr::set_label_text(const ::std::string& value) {
  
  label_text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ascend.presenter.proto.Rectangle_Attr.label_text)
}
#if LANG_CXX11
inline void Rectangle_Attr::set_label_text(::std::string&& value) {
  
  label_text_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ascend.presenter.proto.Rectangle_Attr.label_text)
}
#endif
inline void Rectangle_Attr::set_label_text(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  label_text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ascend.presenter.proto.Rectangle_Attr.label_text)
}
inline void Rectangle_Attr::set_label_text(const char* value, size_t size) {
  
  label_text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ascend.presenter.proto.Rectangle_Attr.label_text)
}
inline ::std::string* Rectangle_Attr::mutable_label_text() {
  
  // @@protoc_insertion_point(field_mutable:ascend.presenter.proto.Rectangle_Attr.label_text)
  return label_text_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Rectangle_Attr::release_label_text() {
  // @@protoc_insertion_point(field_release:ascend.presenter.proto.Rectangle_Attr.label_text)
  
  return label_text_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Rectangle_Attr::set_allocated_label_text(::std::string* label_text) {
  if (label_text != NULL) {
    
  } else {
    
  }
  label_text_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), label_text);
  // @@protoc_insertion_point(field_set_allocated:ascend.presenter.proto.Rectangle_Attr.label_text)
}

// -------------------------------------------------------------------

// PresentImageRequest

// .ascend.presenter.proto.ImageFormat format = 1;
inline void PresentImageRequest::clear_format() {
  format_ = 0;
}
inline ::ascend::presenter::proto::ImageFormat PresentImageRequest::format() const {
  // @@protoc_insertion_point(field_get:ascend.presenter.proto.PresentImageRequest.format)
  return static_cast< ::ascend::presenter::proto::ImageFormat >(format_);
}
inline void PresentImageRequest::set_format(::ascend::presenter::proto::ImageFormat value) {
  
  format_ = value;
  // @@protoc_insertion_point(field_set:ascend.presenter.proto.PresentImageRequest.format)
}

// uint32 width = 2;
inline void PresentImageRequest::clear_width() {
  width_ = 0u;
}
inline ::google::protobuf::uint32 PresentImageRequest::width() const {
  // @@protoc_insertion_point(field_get:ascend.presenter.proto.PresentImageRequest.width)
  return width_;
}
inline void PresentImageRequest::set_width(::google::protobuf::uint32 value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:ascend.presenter.proto.PresentImageRequest.width)
}

// uint32 height = 3;
inline void PresentImageRequest::clear_height() {
  height_ = 0u;
}
inline ::google::protobuf::uint32 PresentImageRequest::height() const {
  // @@protoc_insertion_point(field_get:ascend.presenter.proto.PresentImageRequest.height)
  return height_;
}
inline void PresentImageRequest::set_height(::google::protobuf::uint32 value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:ascend.presenter.proto.PresentImageRequest.height)
}

// bytes data = 4;
inline void PresentImageRequest::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PresentImageRequest::data() const {
  // @@protoc_insertion_point(field_get:ascend.presenter.proto.PresentImageRequest.data)
  return data_.GetNoArena();
}
inline void PresentImageRequest::set_data(const ::std::string& value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ascend.presenter.proto.PresentImageRequest.data)
}
#if LANG_CXX11
inline void PresentImageRequest::set_data(::std::string&& value) {
  
  data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ascend.presenter.proto.PresentImageRequest.data)
}
#endif
inline void PresentImageRequest::set_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ascend.presenter.proto.PresentImageRequest.data)
}
inline void PresentImageRequest::set_data(const void* value, size_t size) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ascend.presenter.proto.PresentImageRequest.data)
}
inline ::std::string* PresentImageRequest::mutable_data() {
  
  // @@protoc_insertion_point(field_mutable:ascend.presenter.proto.PresentImageRequest.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PresentImageRequest::release_data() {
  // @@protoc_insertion_point(field_release:ascend.presenter.proto.PresentImageRequest.data)
  
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PresentImageRequest::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    
  } else {
    
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:ascend.presenter.proto.PresentImageRequest.data)
}

// repeated .ascend.presenter.proto.Rectangle_Attr rectangle_list = 5;
inline int PresentImageRequest::rectangle_list_size() const {
  return rectangle_list_.size();
}
inline void PresentImageRequest::clear_rectangle_list() {
  rectangle_list_.Clear();
}
inline const ::ascend::presenter::proto::Rectangle_Attr& PresentImageRequest::rectangle_list(int index) const {
  // @@protoc_insertion_point(field_get:ascend.presenter.proto.PresentImageRequest.rectangle_list)
  return rectangle_list_.Get(index);
}
inline ::ascend::presenter::proto::Rectangle_Attr* PresentImageRequest::mutable_rectangle_list(int index) {
  // @@protoc_insertion_point(field_mutable:ascend.presenter.proto.PresentImageRequest.rectangle_list)
  return rectangle_list_.Mutable(index);
}
inline ::ascend::presenter::proto::Rectangle_Attr* PresentImageRequest::add_rectangle_list() {
  // @@protoc_insertion_point(field_add:ascend.presenter.proto.PresentImageRequest.rectangle_list)
  return rectangle_list_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ascend::presenter::proto::Rectangle_Attr >*
PresentImageRequest::mutable_rectangle_list() {
  // @@protoc_insertion_point(field_mutable_list:ascend.presenter.proto.PresentImageRequest.rectangle_list)
  return &rectangle_list_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ascend::presenter::proto::Rectangle_Attr >&
PresentImageRequest::rectangle_list() const {
  // @@protoc_insertion_point(field_list:ascend.presenter.proto.PresentImageRequest.rectangle_list)
  return rectangle_list_;
}

// -------------------------------------------------------------------

// PresentImageResponse

// .ascend.presenter.proto.PresentDataErrorCode error_code = 1;
inline void PresentImageResponse::clear_error_code() {
  error_code_ = 0;
}
inline ::ascend::presenter::proto::PresentDataErrorCode PresentImageResponse::error_code() const {
  // @@protoc_insertion_point(field_get:ascend.presenter.proto.PresentImageResponse.error_code)
  return static_cast< ::ascend::presenter::proto::PresentDataErrorCode >(error_code_);
}
inline void PresentImageResponse::set_error_code(::ascend::presenter::proto::PresentDataErrorCode value) {
  
  error_code_ = value;
  // @@protoc_insertion_point(field_set:ascend.presenter.proto.PresentImageResponse.error_code)
}

// string error_message = 2;
inline void PresentImageResponse::clear_error_message() {
  error_message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PresentImageResponse::error_message() const {
  // @@protoc_insertion_point(field_get:ascend.presenter.proto.PresentImageResponse.error_message)
  return error_message_.GetNoArena();
}
inline void PresentImageResponse::set_error_message(const ::std::string& value) {
  
  error_message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ascend.presenter.proto.PresentImageResponse.error_message)
}
#if LANG_CXX11
inline void PresentImageResponse::set_error_message(::std::string&& value) {
  
  error_message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ascend.presenter.proto.PresentImageResponse.error_message)
}
#endif
inline void PresentImageResponse::set_error_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  error_message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ascend.presenter.proto.PresentImageResponse.error_message)
}
inline void PresentImageResponse::set_error_message(const char* value, size_t size) {
  
  error_message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ascend.presenter.proto.PresentImageResponse.error_message)
}
inline ::std::string* PresentImageResponse::mutable_error_message() {
  
  // @@protoc_insertion_point(field_mutable:ascend.presenter.proto.PresentImageResponse.error_message)
  return error_message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PresentImageResponse::release_error_message() {
  // @@protoc_insertion_point(field_release:ascend.presenter.proto.PresentImageResponse.error_message)
  
  return error_message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PresentImageResponse::set_allocated_error_message(::std::string* error_message) {
  if (error_message != NULL) {
    
  } else {
    
  }
  error_message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), error_message);
  // @@protoc_insertion_point(field_set_allocated:ascend.presenter.proto.PresentImageResponse.error_message)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace presenter
}  // namespace ascend

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::ascend::presenter::proto::OpenChannelErrorCode> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ascend::presenter::proto::OpenChannelErrorCode>() {
  return ::ascend::presenter::proto::OpenChannelErrorCode_descriptor();
}
template <> struct is_proto_enum< ::ascend::presenter::proto::ChannelContentType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ascend::presenter::proto::ChannelContentType>() {
  return ::ascend::presenter::proto::ChannelContentType_descriptor();
}
template <> struct is_proto_enum< ::ascend::presenter::proto::ImageFormat> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ascend::presenter::proto::ImageFormat>() {
  return ::ascend::presenter::proto::ImageFormat_descriptor();
}
template <> struct is_proto_enum< ::ascend::presenter::proto::PresentDataErrorCode> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ascend::presenter::proto::PresentDataErrorCode>() {
  return ::ascend::presenter::proto::PresentDataErrorCode_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_presenter_5fmessage_2eproto__INCLUDED
